#!/usr/bin/env bash

# http://stackoverflow.com/questions/59895/can-a-bash-script-tell-which-directory-it-is-stored-in
g_dotvim_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

pushd "${g_dotvim_dir}"
git submodule update --init --recursive
pushd cquery
./waf configure
./waf build
popd
popd
